# Generated by Django 4.2.3 on 2023-12-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0002_teacher_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="username",
        ),
    ]
