# Generated by Django 4.2.3 on 2023-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0003_remove_teacher_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
