# Generated by Django 4.2.3 on 2024-02-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_student_section'),
        ('portals', '0004_teacher_username'),
    ]

    operations = [
    ]
