# Generated by Django 4.2.3 on 2024-03-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0006_remove_student_batch_remove_student_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
