# Generated by Django 4.2.3 on 2024-03-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0007_student_first_name_student_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
    ]
