# Generated by Django 4.2.3 on 2024-03-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0008_remove_student_first_name_remove_student_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="roll_no",
            new_name="StudentID",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="section",
        ),
        migrations.AddField(
            model_name="student",
            name="cnic",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="father_occupation",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="marital_status",
            field=models.CharField(
                choices=[("S", "Single"), ("M", "Married"), ("O", "Other")],
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="nationality",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="religion",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
