# Generated by Django 4.2.3 on 2024-03-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0009_rename_roll_no_student_studentid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Sinle", "Single"),
                    ("Married", "Married"),
                    ("Other", "Other"),
                ],
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
