# Generated by Django 4.2.3 on 2024-03-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0011_alter_student_studentid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="StudentID",
            field=models.CharField(
                editable=False,
                max_length=6,
                unique=True,
                verbose_name="Registration ID",
            ),
        ),
    ]
