# Generated by Django 4.2.3 on 2024-03-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0012_alter_student_studentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
