# Generated by Django 4.2.3 on 2024-03-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0013_student_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="cnic",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="date_of_birth",
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Sinle", "Single"),
                    ("Married", "Married"),
                    ("Other", "Other"),
                ],
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="nationality",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="office_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="religion",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
