# Generated by Django 4.2.3 on 2024-03-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0016_course_degree_department_school_semesterdetails_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="program_description",
        ),
    ]
