# Generated by Django 4.2.3 on 2024-03-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0017_remove_program_program_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="degree",
            name="department",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="portals.department",
            ),
        ),
    ]
