# Generated by Django 4.2.3 on 2024-03-26 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0018_degree_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_description",
        ),
        migrations.RemoveField(
            model_name="degree",
            name="degree_description",
        ),
    ]
