# Generated by Django 4.2.3 on 2024-03-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0019_remove_course_course_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portals.department",
            ),
        ),
    ]
