# Generated by Django 4.2.3 on 2024-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0020_course_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Other", "Other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Other", "Other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
