# Generated by Django 4.2.3 on 2024-04-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0022_alter_degree_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portals.department",
            ),
        ),
        migrations.AlterField(
            model_name="degree",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portals.program",
            ),
        ),
    ]
