# Generated by Django 4.2.3 on 2024-04-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0023_alter_degree_department_alter_degree_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
    ]
