# Generated by Django 4.2.3 on 2024-04-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0025_user_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="department_intro",
        ),
    ]
